### ISSUE TITLE
Just a question 

### ISSUE THREAD

**Issue by ant5** [letoram/arcan#105]
I'm sorry I just wandering to clarify my understanding of arkan.
Does a "frameserver" term mean the same as a "client" term in arkan?  (As I understand a client (frameserver) is a program (process) with own logic which provide "visual representation and aural representation". Or I missing many things?)

**Comment by letoram** [comment]
You can consider frameservers to be specialized clients that we trust to a higher degree for a certain set of tasks (role/archetype). So there is possibly one frameserver for decode (parsers), one for encode (recording, streaming), one for terminal and so on - and they are written explicitly to fulfil that role.

**Comment by ant5** [comment]
Thank you for response. I have more questions, if you do not mind.
If I want to write a program exclusive to arcan what should I do?  The program will be under visual management of druden. What API should I use?
Is there a sample of "Hello, world"?

**Comment by letoram** [comment]
Three options.

1. Write a lua appl and use arcan_lwa /path/to/folder to start it. There's https://github.com/letoram/arcan/wiki/Exercises as a text guide for this, with the solutions in https://github.com/letoram/arcan/tree/master/tests/exercises here.

2. (C) For a CLI application, there's the (near-future stable) TUI API, skeleton here: https://github.com/letoram/arcan/blob/master/tests/frameservers/tui_test/tui_test.c

3. (C) There's also the unstable API (as in, be prepared to recompile when the arcan build changes), it's only documented in header files with my testing applications appearing here: https://github.com/letoram/arcan/tree/master/tests/frameservers

**Comment by letoram** [comment]
If you have more questions, grab me on IRC - it's typically way easier. Anyhow, closing the issue.
