### ISSUE TITLE
Install error in stage 2

### ISSUE THREAD

**Issue by gnh1201** [letoram/arcan#111]
I installed libapr and libvlc. but can not find when to build. How can I do?

```
-- Stage 2, Frameservers / Hijack
(net) disabled, libapr not found
(game/libretro) Enabling 3D support.
(decode) disabled, libvlc not found
(encode) building with vnc support
Frameservers:  terminal game encode encode remoting avfeed
Hijack Libraries:       Disabled
```

**Comment by letoram** [comment]
those are not build errors by themselves, just a note that these features (networking, which you don't want anyhow - right now, wait for 0.6) och video decoding (which is a bit more interesting).

Check the CMakeCache.txt file, you can find =NOT_FOUND on some dependencies that should clue you in as to what you are missing - maybe your distribution splits libvlc into developer headers, or libvlc-core or something. If you are really certain, you can modify the cache file where it says NOT_FOUND and point it there yourself.
