### ISSUE TITLE
graphics platform improvement

### ISSUE THREAD

**Issue by letoram** [letoram/arcan#124]
Planned enchancements short/near-term:

- [x] WORLDID- free render mode (saves memory and bandwidth)
- [x] consolidate synchronization into shared conductor
- [ ] EGL_DISPLAY- free mode (requires drmAddFB2)
   - [ ] direct scanout on map_display on externally bound vstore (requires drmAddFB2)
- [x] headless platform
- [ ] modifiers support for dma-buf
- [x] clean up configuration (comes with #114)
- [ ] allow shader "variant" slots based on source (external, external/planar)/platform
- [x] allow floating-point and MSAA on rendertargets
- [ ] AGP based dirty region
- [ ] AGP vstore transforms (multi-FD, YUV repacking, OES_EXTERNAL repacking)
- [ ] hw- scrolling (vstore a, vstore b, scroll region, scroll direction)
- [ ] automatic MSAA-less copy-out
- [ ] optional GL4 features
   - [ ] zero-copy using buffer pinning
   - [ ] external_object
- [ ] EGL_EXT_platform_device for shmif on eglstreams

**Comment by Immortalin** [comment]
@letoram, for 2D stuff, how is its performance compared to Google's Skia engine?

**Comment by letoram** [comment]
Educated guess: noticeably better and noticeably worse - with that I mean everything you can think of is in Skia, it's like half a million lines of code and its very uneven, some parts you can see there's motherly care and serious effort behind and some parts are just bare minimum/yolo 12 years ago - it's hard to even get an overview. By the looks of it is that animations, transforms, hierarchies, clipping, caching, invalidation are in my favour, dynamic SVG- like vector graphics are in theirs - with GPU drawing that is, where 2D is just a simple configuration of the same stuff you do for 3D.

What matters most is which parts you happen to use - and how easy it is for you to work/change/tune. If all your programming effort is put into getting something to work, you won't get to the point of getting it to work well for your targeted devices. Chances are that the big limiter is actually not the libraries you chose but your decisions, It's one of the absolute hardest areas to get any kind of reliably measure as there's tons of room for tuning towards quality, smoothness or energy consumption and "benchmarking" by doing the same drawing operation over and over is a fool's errand. Worse yet, do you need the CPU for something else at the same time, or are you capped by memory bandwidth? and so on. There's good reason why the GPU vendors have expert teams that they deploy to help "valued customers". 

Define a few _relevant_ use cases, try them out, measure. Anything else is just inane speculation and/or politics.
