### ISSUE TITLE
Arcan won't start with egl-dri

### ISSUE THREAD

**Issue by Caagr98** [letoram/arcan#129]
I'm trying to install this thing, but it's not going particularly well. Compilation with `cmake -DVIDEO_PLATFORM=egl-dri -DSTATIC_SQLITE3=ON -DSTATIC_OPENAL=ON -DSTATIC_FREETYPE=ON ../src; make -j 12` works fine (with a few warnings about snprintf and various deprecation), but running it (in VT 2) just gives errors.

```
$ ./arcan -p ../data/resources ../data/appl/welcome
Empty database encountered, running default DDL queries.
egl-dri::2734:setup_cards_basic(): trying [basic/auto] setup on /dev/dri/card0

i965_dri.so does not support the 0xffffffff PCI ID.
egl-dri::1383:setup_node(): failed to initialize EGL
egl-dri::2567:try_node(): setup/configure [0](4:/dev/dri/card0)
egl-dri::1457:setup_node_egl(): EGLStreams, query failed or no devices found
egl-dri::2559:try_node(): couldn't open (4:/dev/dri/card0) in EGLStreams mode
egl-dri::2742:setup_cards_basic(): node setup failed

egl-dri::2734:setup_cards_basic(): trying [basic/auto] setup on /dev/dri/card1

egl-dri::2734:setup_cards_basic(): trying [basic/auto] setup on /dev/dri/card2

egl-dri::2734:setup_cards_basic(): trying [basic/auto] setup on /dev/dri/card3

platform_video_init() failed.
Error: couldn't initialize video subsystem. Check permissions,  try other video platform options (-f, -w, -h)
Video platform configuration options:
(use ARCAN_VIDEO_XXX=val for env, video_xxx for db)
	[ for multiple devices, append _n to key (e.g. device_2=) ] - 
	device=/path/to/dev - for multiple devices suffix with _n (n = 2,3..)
	device_buffer=method - set buffer transfer method (gbm, streams)
	device_libs=lib1:lib2 - libs used for device
	device_connector=ind - primary display connector index
	device_master - fail hard if drmMaster can't be obtained
	device_wait - loop until an active connector is found

Graphics platform configuration options:
(use ARCAN_GRAPHICS_XXX=val for env, graphics_xxx=val for db)

Video platform initialization failed
zsh: abort (core dumped)  ./arcan -p ../data/resources ../data/appl/welcome
```

`/dev/dri` contains a `card0` and `renderD128`, both of which I (according to `test -r`/`w`) have both read and write access to. Is there something I've missed?

P.S. The SDL version appears to work fine, at least with the welcome appl.

**Comment by letoram** [comment]
You can cmake with -DCMAKE_BUILD_TYPE=Debug for much more verbose logging, but this smells like a DRM_MASTER issue. Short story, there's a hidden root-only capability required to use the card node and it relates to how display managers, display servers and so on are supposed to negotiate display access - I'm guessing something else on your system holds this capability.

There's an ugly protocol for dealing with this (which may or may not involve distribution specific stuff like logind, proxy-suid launchers), - I've avoided implementing support for that pending a refactor of the gpu- configuration code.

Two options, if no-one has tried to use the card0 already (so boot into console and run without Xorg on a VT), the first user with device permissions will get a pseudo-"drmMaster" capability without being root. The other is well, icky, i.e. being root.

Protip (and I should really update the welcome appl): use ../tests/interactive/eventtest instead for testing when running from the console, as it has a safety shutdown timeout if no keyboard is detected or present.

**Comment by Caagr98** [comment]
Tried rebooting and running Arcan before anything else (except the VT and Zsh, obviously), and tried running with sudo. Neither noticeably affected the output.

**Comment by letoram** [comment]
interesting - the "i965_dri.so does not support the 0xffffffff PCI ID." message hint that this might be further down in the graphics stack (mesa, libdrm, driver).

1. does weston (wayland reference compositor) display the same error?
2. more data: kernel & libdrm version + output from debug build of arcan with LIBGL_DEBUG=verbose environment and if there's anything in dmesg.

**Comment by Caagr98** [comment]
Weston works fine. (Well, it starts. The terminal just fades away immediately, so it's completely unusable.)

`uname -a` is `Linux Lorence 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux`

`libdrm` is version `2.4.88-1` according to pacman

`LIBGL_DEBUG=verbose` adds an extra line `libGL: Can't open configuration file /home/yuki/.drirc: No such file or directory.` just before the `failed to initialize EGL`, but otherwise no difference. (Used as an environment variable. If it was supposed to be a compilation flag, my mistake.)

**Comment by Caagr98** [comment]
Oh, and mesa is version `17.2.5-1`,  and `dmesg` says nothing.

**Comment by letoram** [comment]
the LIBGL_ was indeed an environmental variable - but versions etc. all seems reasonable. Ok so this is narrowed down to the EGL setup itself, (unless weston actually switched to its kms-fb backend, but I don't remember how that part works).

There's another environment variable that should get us closer,  EGL_LOG_LEVEL=debug

**Comment by Caagr98** [comment]
Here's with `EGL_LOG_LEVEL=debug`: [arcan.log](https://github.com/letoram/arcan/files/1475522/arcan.log). It mentions something about x11, not sure if that's relevant.

**Comment by letoram** [comment]
it's relevant, and likely the reason, i.e. it couldn't derive the EGL platform from the display handle I provide. There's an extension I can use to get around that, adding to the work-queue, but you should be able to test/ override this with the environment:
EGL_PLATFORM=drm

**Comment by Caagr98** [comment]
[arcan.log](https://github.com/letoram/arcan/files/1475585/arcan.log)

Doesn't seem to change anything.

**Comment by letoram** [comment]
I'll try implement the extension, bbiab.

**Comment by letoram** [comment]
There, if you synch to the latest, 708988dfeedbfd9e1732c044a1968df67b555f1d commit) - any change?

**Comment by Caagr98** [comment]
Now it starts, but switching framebuffer back to the X session crashes everything, and I couldn't find any other way to close the welcome appl. One of the readmes (don't remember which) does state that switching framebuffers is unsupported, though.

Waiting for the event test to close and starting an X afterwards works fine, though.

P.S. Wow you're fast.

**Comment by letoram** [comment]
It is "supported" as far as is possible, but it's an inherently broken concept - I have machines here where it works perfectly, and a few where I get kernel panics if I switch the kvm- at the same time.

Poke me on IRC for generic stuff, push another issue for the next thing you run into, I should add a shutdown timer to the welcome appl though ;-)
