### ISSUE TITLE
Keyboard not found

### ISSUE THREAD

**Issue by tallero** [letoram/arcan#131]
While trying to start durden I get:

>>~/Projects/arcan/build$ arcan ../../durden/durden
i965_dri.so does not support the 0xffffffff PCI ID.
AL lib: (EE) ALCplaybackOSS_open: Could not open /dev/dsp: No such file or directory
(durden) arcan reported no available translation capable devices (keyboard), cannot continue without one.

>>Script failure:
  ../../durden/durden/display.lua:908: attempt to index a nil value
C-entry point:  push event( input ) .

>>Handing over to recovery script (or shutdown if none present).
Lua VM failed with no fallback defined, (see -b arg).

Connecting an USB keyboard does not change the error. Welcome app starts and after some bump stops.

Prio starts but does not see keyboard nor touchpad nor USB mouse

**Comment by letoram** [comment]
Does the user you are running as have permission to open /dev/input/* ?

https://github.com/letoram/arcan/wiki/egl-dri check the 'Second, permissions and devices. ' part.
Since you have a source installation, you can also try the tests/interactive/eventtest appl

**Comment by tallero** [comment]
Thank you very much.
Adding the user to input solved the problem, now keyboard and mouse work. Two more questions:
is it possible to run X11/wayland apps with egl-dri?
is there a way to change keyboard layout? Arrow keys are broken on my laptop.

**Comment by letoram** [comment]
running X11 apps - there's https://github.com/letoram/xarcan
it looks / works similar to how you would use xephyr and the likes, i.e. it is an "xserver in a window" in which you run a window manager etc. as normal.

running wayland apps - see src/tools/waybridge in the arcan codebase.

keyboard layout - 
if you had libxkbcommon available at build time (it's an optional dependency) you can specify old x keyboard layouts via the XKB_blabla environment variables it supports, and you need this for wayland unfortunately.

durden has its own take on how keyboard layouts should be handled, http://durden.arcan-fe.com/input#keyboard but for your broken arrow keys, you can rebind those in-gui, for instance: global/input/keyboard/maps/bind keysym/left 

UI tools for doing this (and OSD keyboards and trackpad tuning) is coming eventually :-)
