### ISSUE TITLE
cmake issue

### ISSUE THREAD

**Issue by tekjanson** [letoram/arcan#132]
[tekjanson@Behemoth:build]$  cmake -DCMAKE_BUILD_TYPE="Debug" -DVIDEO_PLATFORM=sdl ../src

Audio/Video/Input Support:
(req.)	-DVIDEO_PLATFORM=egl-dri, sdl, egl-gles
	-DAGP_PLATFORM=gl21, gles2, gles3, stub

Cmake Options:
	-DCMAKE_BUILD_TYPE=[Debug|Release|Profile|DebugTrace]
	-DENABLE_SIMD=[On|Off] - Enable SIMD optimized instructions
		-DSIMD_ALIGNED=[Off|On] - SIMD support assumes 16-byte alignment
	-DENABLE_LTO=[Off|On] - Build with Link-Time Optimizations

Dependency Management:
	-DSTATIC_SQLITE3=[Off|On] - In-source SQLite3
	-DSTATIC_OPENAL=[Off|On] - In-source OpenAL, see external/README
	-DSTATIC_FREETYPE=[Off|On] - In-source Freetype
	-DFORCE_NOHARFBUZZ=[Off|On] - Never use harfbuzz text shaping

Optional engine flags:
	-DENABLE_LWA=[Off|On] - Build LWA Arcan client (nesting support)
	-DDISABLE_JIT=[Off|On] - Don't Link with luajit51 (even if found)
	-DNO_FSRV=[Off|On] - Build Arcan without support for frameservers
	-DSHMIF_TUI_ACCEL=[Off|On] - Build Tui with GPU support (ARCAN_ARG=accel=1)

Frameserver flags:
Decode:${CL_RST}
	-DFSRV_DECODE_UVC={$CL_GRN}[Off|On] - Add support for libuvc- USB video camera

Install / Autodetection Overrides:
	-D(DISABLE_FSRV_ (encode, decode, net, remoting, terminal, game)=ON 
	-D(APPL_DEST, RES_DEST, APIMAN_DEST, MAN_DEST)=/some/path 

------------------*Debug Build*--------------------
Debug Specific Setting:
	LUA_TRACE_METHOD=[off|stderr|coverage]

-- Stage 1: dependencies and configuration
CMake Error at CMakeLists.txt:8 (_message):
  Could not find Sqlite3
Call Stack (most recent call first):
  platform/cmake/modules/FindSQLITE3.cmake:52 (MESSAGE)
  CMakeLists.txt:345 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/tekjanson/Documents/Personal/arcan/build/CMakeFiles/CMakeOutput.log".

**Comment by VegaDeftwing** [comment]
are you building on arch? I had the same issue. Following the statically linked instructions I got further, but still have some other build issues.

**Comment by tekjanson** [comment]
No I was trying it on Ubuntu 16.04, by tooling around I got what I thought might be further but I wasn't sure.

**Comment by letoram** [comment]
This is not just a case of the missing 'sqlite3' dependency? (alternatively, go with the static -DSTATIC_SQLITE3=ON ), afaik. earnestlys builds @ https://github.com/Earnestly/pkgbuilds/blob/master/arcan-git/PKGBUILD havn't had any arch-linux problems.
