### ISSUE TITLE
Is it worth integrating pipewire into arcan?

### ISSUE THREAD

**Issue by ranomier** [letoram/arcan#135]
I didn't found a forum to write this. So you can close this ticket any time you want. No hard feelings.

Could it be a good idea to integrate pipewire into arcan?

PS: I realy like your work :3 :+1:

_Sent from my Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by letoram** [comment]
Our communication mostly revolves around IRC.

As for Pipewire -- there is nothing compelling inside of it that we don't have here already. On top of that, they are have hard dependencies (D-Bus), explicitly blacklisted in the project for security and sanity reasons.

Should there appear a relevant user need down the line, the hooks for providing non-default implementations of the frameserver_decode and frameserver_encode roles are already there. 

PS: thanks 👍

**Comment by ranomier** [comment]
Cool good to know, I will look into the security issues related to dbus its new to me.
