### ISSUE TITLE
CMake error on find_package(Tesseract)

### ISSUE THREAD

**Issue by rexy712** [letoram/arcan#138]
I'm trying to configure with the command listed in the readme.
`cmake -DCMAKE_BUILD_TYPE="Debug" -DVIDEO_PLATFORM=sdl ../src`
It gets to stage 2 then spits out an error when searching for tesseract. I hunted down the exact spot: src/frameserver/encode/default/CMakeLists.txt line 50 `find_package(Tesseract)`. If I comment out this line, the configure succeeds.

I also tried updating cmake from 3.9.6 to 3.13.2 and same issue.

Here's the exact error message

```
-- Stage 1: dependencies and configuration
linux-usb	detected

---- Configuration results:
compiler	GNU
video   	sdl
accel   	gl21
audio   	openal
input   	sdl
headless	egl-dri-rnode
lua     	luajit51 static

-- Stage 2, Frameservers / Hijack
shmif-tui	shaping:harfbuzz
game/retro	3D support (lwa)
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:619 (if):
  if given arguments:

    "NOT" "DEFINED" "__pkg_config_checked_Tesseract" "OR" "__pkg_config_checked_Tesseract" "LESS" "OR" "NOT" "Tesseract_FOUND" "OR" "(" "NOT" "lept" "STREQUAL" "" "AND" "NOT" "" "STREQUAL" "tesseract;lept" ")" "OR" "(" "lept" "STREQUAL" "" "AND" "NOT" "" "STREQUAL" "tesseract" ")"

  Unknown arguments specified
Call Stack (most recent call first):
  platform/cmake/modules/FindTesseract.cmake:2 (pkg_check_modules)
  frameserver/encode/default/CMakeLists.txt:50 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by letoram** [comment]
The FindPkgConfig error messages are terrible, will see what I can do about that. It's likely that it is looking for the 'leptonica' dependency (tesseract package might be split up into two depending on distribution).
