### ISSUE TITLE
Use submodules instead of manual clone.sh?

### ISSUE THREAD

**Issue by Elronnd** [letoram/arcan#144]
This makes it so that the build instructions are simpler (clone just has to be git clone --recursive instead of straight clone), and also means that you can tag a 'known-good' upstream version.

**Comment by letoram** [comment]
Submodules were used for the purpose back in ~2014, but caused more harm than good. The interface has no doubt improved, but going forward the intention is rather that the entire external/ will be made obsolete. The only showstopper at the moment are the custom openal patches needed for the _lwa build. These will disappear with the pending audio subsystem refactor.

**Comment by Elronnd** [comment]
👍
