### ISSUE TITLE
Trying to build on NetBSD

### ISSUE THREAD

**Issue by brunomaximom** [letoram/arcan#189]
Arcan build cannot find libdrm on NetBSD. Attached CMakeCache.txt
[CMakeCache.txt](https://github.com/letoram/arcan/files/4496893/CMakeCache.txt)

**Comment by iceiceleo** [comment]
@brunomaximom try this https://github.com/letoram/arcan/pull/200

**Comment by iceiceleo** [comment]
it would wonderful to get this to pkgsrc

**Comment by letoram** [comment]
been fixed for a while.
