### ISSUE TITLE
Arcan doesn't print an error message when execvp fails

### ISSUE THREAD

**Issue by magiblot** [letoram/arcan#190]
When attempting to run arcan from a X session with the command given as an example in the readme (`./arcan -T ../data/scripts -p ../data/resources ../data/appl/welcome`), nothing seems to happen. Arcan exits immediately without giving any hint of what went wrong.

A bit of debugging reveals that my build is missing `arcan_sdl` for some reason, which causes  arcan to fail in https://github.com/letoram/arcan/blob/c5af125adac72d002dfc3254f04af17ba83a878c/src/engine/arcan_main.c#L352

It might be a good idea to print an error message in these cases to help the user understand what went wrong. At least, it should not fail silently.

Thank you!

**Comment by magiblot** [comment]
Regarding `arcan_sdl`, I have to run `cmake` twice to have it build. And then I have to add it to `PATH`.

**Comment by letoram** [comment]
Noted, will do and thanks. Regarding the twice- build part - I tested with cmake here and got both binaries produced on a single run for a fresh build folder. Did you flush entirely or might the problem have been cmake caching?

**Comment by magiblot** [comment]
I don't know. I removed everything in `build` and could reproduce the issue again.

[build.log](https://github.com/letoram/arcan/files/4544052/build.log)

**Comment by akavel** [comment]
Just for the record, I also stumbled into this. I was getting empty output from `./arcan` and no idea WTF is going on, took me quite some time until I finally thought to open the Issues list to see if there's something that may be relevant. Found this, and adding `PATH=$PATH:.` surely helped to finally start getting any output, namely some error messages that I can now start trying to resolve...
