### ISSUE TITLE
Error: couldn't initialize video subsystem.

### ISSUE THREAD

**Issue by akavel** [letoram/arcan#191]
I built arcan on Ubuntu, and I'm trying to run it, but I'm getting an error message like below:

```
akavel@mateusz-SVS1511T9ES:~/prog/arcan-nix$ ARCAN_VIDEO_MULTISAMPLES=1 LIBGL_DEBUG=verbose EGL_LOG_LEVEL=debug PATH=$PATH:./result/bin/ ARCAN_BINPATH=./result/bin ./result/bin/arcan -T ./arcan/data/scripts -p ./arcan/data/resources ./arcan/data/appl/welcome 
arcan_video_init(), Couldn't open OpenGL display,attempting without MSAA
platform_video_init() failed.
Error: couldn't initialize video subsystem. Check permissions,  try other video platform options (-f, -w, -h)
Video platform configuration options:
(use ARCAN_VIDEO_XXX=val for env, or arcan_db add_appl_kv arcan video_xxx for db)
	ignore_dirty - always update regardless of 'dirty' state
	ARCAN_VIDEO_MULTISAMPLES=1 - attempt to enable multisampling

Graphics platform configuration options:
(use ARCAN_GRAPHICS_XXX=val for env, graphics_xxx=val for db)

Video platform initialization failed
```

Any idea what I might be doing wrong, or what I might need to tweak to make it work? Or how to debug this further? I tried running the same command with `sudo`, but the error message seems exactly the same. The various options like MULTISAMPLES etc. are what I tried to add to maybe resolve it or get some more info; without them I'm getting the same error too. I also tried `-f` and stuff like `-w 1024 -h 768` but also no change. Any ideas?

**Comment by letoram** [comment]
Does any other SDL/SDL2 application run on that setup. does glxgears work? This seems to be in those parts of the stack, there is not much arcan related code that gets to run.

**Comment by akavel** [comment]
Ahhh, ok, your question helped me find out, that because I built Arcan with Nix, I had to use https://github.com/guibou/nixGL to run it. The welcome window works now, thanks!
