### ISSUE TITLE
i18n problem in console. International characters not visible

### ISSUE THREAD

**Issue by dikonov** [letoram/arcan#203]
I am running `arcan console` in the Russian locale and it fails to display most non-ascii characters. All text, UI labels, etc. are not visible. See the screenshot.

```
$ locale
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```
The included default.ttf has cyrillic glyphs, so it should work.

![i18nbug](https://user-images.githubusercontent.com/4271322/99793129-39ee9780-2b39-11eb-8529-9455c3e8f4b0.png)

**Comment by letoram** [comment]
default.ttf is shaped / used for other UI elements - if not provided a font the terminal will fallback to a builtin one which looks like the right side one. There is some way of going xxd on a pixel font to swap out the builtin one for custom psfs as well (or add cyrilic glyphs to it: src/shmif/tui/raster/pixelfont.c).

Make sure the font you want is in whatever the sys font namespace is (resources/fonts or ARCAN_FONTPATH env.):

    arcan_db add_appl_kv console terminal_font myfont.ttf
    arcan_db add_appl_kv console font_sz 10

or whatever pt size you want.

**Comment by dikonov** [comment]
Thanks! 
The first command works with either the default.ttf (which lacks pseudographics for mc panels) or my system ttf fonts after copying them to the ../arcan/resources/fonts. The terminal starts to display UTF-8 correctly.

The second command does nothing. The font size is always gigantic and I cannot change it. 

_I'll have a look at the pixelfont.c if I manage to get arcan display safespaces in my VivePro HMD._

**Comment by letoram** [comment]
apparently the key was font_size and not font_sz.
