### ISSUE TITLE
Arcan + arcan_vr fails to use HMD as a display

### ISSUE THREAD

**Issue by dikonov** [letoram/arcan#204]
I have a working HTC Vive Pro, which I can use via SteamVR. 

I have built, rpm-packaged and installed OpenXR, monado, OpenHMD, Arcan, arcan_vr and safespaces. My goal is to get a working VR desktop.

SteamVR works as it should, all OSS libs and drivers detect the hardware and receive gyro data (I have no access to my lighthouses right now). Arcan happily runs arcan_vr and safespaces inside a xorg window.

`arcan /usr/share/safespaces device=basic`

produces an SBS image, which rotates according to the HMD motion, but

`arcan /usr/share/safespaces device=vivepro`

produces a static monoscopic window, which does not react to the HMD motion, and displays NOTHING in the HMD.

Here is a sample of the arcan_vr console output:
```
$ arcan_vr
console detected, switching to arcan-less mode
:98:openhmd_init(): 1 devices found
[II] 0bb4:0309 0007:0007:00
[II] opening
[II] 28de:2300 0007:000a:00
[II] opening
[II] 28de:2300 0007:000a:01
[II] 28de:2300 0007:000a:02
[II] manufacturer: 'HTC'
[II] product: 'VIVE Pro'
[II] serial number: '206D31514B53'
[II] power on magic: 64
[II] Enable Pro IMU magic: 64

:144:openhmd_init(): vendor:  HTC/Valve
:145:openhmd_init(): product: HTC Vive
:146:openhmd_init(): path:    0
:148:vrbridge_alloc_limb(): allocated limb slot 2, id: 0 (mask: 4)
:122:device_rescan(): vrbridge:rescan() - found 
vr bridge running in offline mode
:42:openhmd_sample(): orientation: -0.000000, -0.000000, -0.000000, 1.000000
:42:openhmd_sample(): orientation: -0.000000, -0.000000, -0.000000, 1.000000
:42:openhmd_sample(): orientation: -0.000000, -0.000000, -0.000000, 1.000000
---8<---------
:42:openhmd_sample(): orientation: 0.910676, -0.000641, -0.024127, 0.412416
:42:openhmd_sample(): orientation: 0.910676, -0.000641, -0.024127, 0.412416
:42:openhmd_sample(): orientation: 0.910677, -0.000644, -0.024127, 0.412414
:42:openhmd_sample(): orientation: 0.910677, -0.000644, -0.024127, 0.412414
```

Trying to run arcan without xorg running (init 3) changes nothing. All video output goes only to the main regular display. The HMD stays pitch-black. 

I am aware of a similar bug [safespaces issue 13](https://github.com/letoram/safespaces/issues/13) but the solution provided there is invalid. Vive Pro HMD is not listed among xrandr displays and has no name required to give any randr commands. I feel that it is really an arcan (or arcan_vr) issue.

**Comment by dikonov** [comment]
It might be useful to add that my current notebook setup has 3 GPUs:
```
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Whistler [Radeon HD 6630M/6650M/6750M/7670M/7690M]
0b:00.0 VGA compatible controller: NVIDIA Corporation TU106 [GeForce RTX 2070] (rev a1)
```
The RTX2070 is a eGPU. The HMD is attached to a DP port of the RTX, which uses nvidia binary driver. Nouveau is blacklisted to avoid interference. The HDMI port is taken up by a display emulator plug (used to prevent eGPU from sleeping). nvidia-settings lists the HDMI emulator as the only display device attached. HMD is invisible even there, ... but it still works in SteamVR.

**Comment by letoram** [comment]
So this is really complex and an area that will be rewritten multiple times I am afraid, there are so many edge cases to HMDs that apply nowhere else and judging by new HMDs it is a never-ending story. 90% of safespaces work has practically been banging my head against this problem, made worse by having to put-on, remove, unplug, reboot, analyse trace logs and so on.

The vivepro leaving you with a dead monoscopic window is basically it waiting for the HMD to appear as the listed display. I don't remember the vivepro specifics, but I think it was one of those that it behaves like one display when it is just plugged in (and another if it is plugged in at boot), and then after we activate sampling etc. it unplugs/plugs itself as something else.

For non-Xorg graphics and nvidia - don't expect it to be stable, their driver is quite bad - there are a bunch of environment variables to poke in order for arcan to try and configure it through the nvidia-binary special path, get it working on a normal display through that scenario first (there is a wiki page about it + the output from running arcan --help), use something like tests/interactive/eventtest (it shuts down after a time of inactivity).

For Xorg graphics, the nvidia driver explicitly blocks HMDs unless you add some option to disable that behavior, that's likely why you don't see it in Xrandr.

**Comment by dikonov** [comment]
For the benefit of the public: The Nvidia option is mentioned in the nvidia driver [README](http://download.nvidia.com/XFree86/Linux-x86/387.22/README/README.txt)
```
Option "AllowHMD" "string"

    Most Virtual Reality Head Mounted Displays (HMDs), such as the HTC VIVE,
    require special image processing. This means it is usually undesirable to
    display the X11 desktop on an HMD. By default, the NVIDIA X driver will
    treat any detected HMDs as disconnected. To override this behavior, set
    the X configuration option "AllowHMD" to "yes", or explicitly list the
    HMDs to allow (any other HMDs will continue to be ignored).

    Examples:
    
        Option "AllowHMD" "yes"

        Option "AllowHMD" "HDMI-0, HDMI-1"
```
It was not present in my eGPU config. I added the option to the /etc/X11/xorg.conf, but ... nothing changed.

**Comment by dikonov** [comment]
Here are some logs:

1. dmesg output after turning on the VR HMD
    [vivepro-linkbox-dmesg.txt](https://github.com/letoram/arcan/files/5579454/vivepro-linkbox-dmesg.txt)
2. OpenXR monado log which complains about the firmware and lack of the lighthouses.
    [VR-monadoprobe.txt](https://github.com/letoram/arcan/files/5579458/VR-monadoprobe.txt)
3. SteamVR console log (Removed Steam IDs)
    [SteamVR-log.txt](https://github.com/letoram/arcan/files/5579479/SteamVR-log.txt)
The result of running SteamVR without Lighthouses is working HMD that shows a blank grey field.

Please, note that I do not have Lighthouses with me right now. All errors about being unable to turn them on are expected.
The HMD firmware may be old (as OpenXR complains), but I shall update it in a week or two, when I get to the lighthouses.
The point is getting the HMD to display something outside of SteamVR.

**Comment by dikonov** [comment]
After running SteamVR, which initializes the HMD, and setting the nvidia `Option "AllowHMD"` I have the following:
- HMD in ON  (small green led glows)
- I can get stereo video from its camera (shows my keyboard and mouse) in Monado (OpenXR client).
  It would be cool to add that camera as a window into the real space or background in safespaces.
- There is still nothing on the HMD's screens
- There are no connected displays in the randr list except for the main notebook display.

**Comment by dikonov** [comment]
Unfortunately, the issue is not solved yet. I am still unable to see arcan and safespaces inside the HMD.

Whenever I run `arcan /usr/share/safespaces device=basic` or `arcan /usr/share/safespaces device=vivepro` the HMD screen turn off. It does not wake after I kill the arcan process. The only way to reset it now is to power-cycle the HMD. 
Device=basic can show safespaces in stereo on the main screen and rotate it well, but the HMD screens shut down.

It must be arcan's own bug now.

**Comment by letoram** [comment]
When you run rested (inside of another display server, like Xorg) the device specific profiles doesn't make sense (i.e. they won't activate as we don't get direct control of the displays, there is a model of having a client 'lease' displays from Xorg, but it won't work with the nvidia blobs anyhow and we never implemented it). You also might need to create a profile of your own if the distortion properties, ipd etc. doesn't feel right.

The device on/off problem is possibly some part of openHMD (arcan_vr delegates it there and the arcan_sdl build that it runs as under Xorg doesn't have any DPMS controls at all) when enabling sampling. Does manually building OpenHMD and its example, then running that have the same effect?

Safespaces has the option to map any arcan compatible client to a background surface, and there should be (if there isn't) a way to create an unmanaged layer of surfaces at fixed positions. I've successfully used a VuzeXR camera mounted on the balcony, streaming to my wallpaper for a live stereo 180SBS.

Afsrv_decode can capture, either through what libvlc supports (ARCAN_ARG=capture:device=0 <-- index based on detection) or through the opt-in libuvc support (not a default build) that has more precise controls (will eventually be used for inside-out outside-in tracking as well) so it is just about mapping that to the right surface.

**Comment by dikonov** [comment]
> ... the device specific profiles doesn't make sense ... You also might need to create a profile of your own if the distortion properties, ipd etc. doesn't feel right.
There is not enough documentation for me to know what options exist in profiles and what are their possible values.

> Does manually building OpenHMD and its example, then running that have the same effect?
The OpenHMD package was built by myself with the goal to run safespaces. 
Yes, the effect is the same. HMD screens darken. The opengl example opens in a window on the main display and works there. The DE is Cinnamon.

_> Safespaces has the option to map any arcan compatible client to a background surface, and there should be (if there isn't) a way to create an unmanaged layer of surfaces at fixed positions. I've successfully used a VuzeXR camera mounted on the balcony, streaming to my wallpaper for a live stereo 180SBS.

Cool! Could you post an example?  I do not know how to instruct arcan to do such stuff. I am a complete noob in controlling arcan and "Mapping a video to a surface" is Chinese to me. It is also unclear how to get that video stream into the arcan environment._

**Comment by dikonov** [comment]
Filed a [bug for OpenHMD](https://github.com/OpenHMD/OpenHMD/issues/316)

**Comment by dikonov** [comment]
OpenHMD dev says that their code works properly and the apps like Safespaces should either use a special compositor (OpenXR provides one) or at least their shader to display to HMD and make a proper HMD picture.

**Comment by letoram** [comment]
Arcan is such a special composer. Using their terminology, it can do both 'extended' mode (sdl2 video platform) _and_ 'direct' mode (egl-dri video platform) in their terminology. What we are trying to get going here is 'extended' due to how problematic 'direct' is on nvidia.

Safespaces do use their glsl shader. That is also not the problem. The problem, from what I understand from your posts:

> Whenever I run arcan /usr/share/safespaces device=basic or arcan /usr/share/safespaces device=vivepro the HMD screen blackens. It does not wake after I kill the arcan process. The only way to reset it is to power-cycle the HMD.

That is what suggests that this might be the commands that OpenHMD sends to the device that is the show stopper here. safespaces delegates opening the device to arcan, that sends it to arcan_vr which uses OpenHMD to do the job. Neither arcan nor arcan_vr sends any commands to Xorg (or the device) that would have an effect on the screen state itself.
