### ISSUE TITLE
Question : looking for wayland environment desktop similar to awesome WM

### ISSUE THREAD

**Issue by deb75** [letoram/arcan#231]
Hello,

I have been using `awesomeWM` for years with great pleasure. But I switched to wayland so that
I am now looking for something similar to it on the wayland side.

The nice feature I would like to have is to be able to extend in any ways the desktop environment with lua,
which was quite easy to do on `awesomeWM`

It seems to me, at first glance, that `durden`, together with `arcan`, could comply with this, am I right ?

In addition, is it possible with `durden` to benefit from a touchscreen, i.e. being able to implement some gestures ? Even if not yet implemented.

Regards

deb75

**Comment by daurnimator** [comment]
> I am now looking for something similar to it on the wayland side.

arcan is a competitor to wayland.

If you're looking for a tiling window manager on wayland, [sway](https://swaywm.org/) is the most popular choice; though you may want to checkout [river](https://github.com/ifreund/river)

**Comment by letoram** [comment]
> > I am now looking for something similar to it on the wayland side.
> 
> arcan is a competitor to wayland.
> 
> If you're looking for a tiling window manager on wayland, [sway](https://swaywm.org/) is the most popular choice; though you may want to checkout [river](https://github.com/ifreund/river)

No. Arcan has a Wayland implementation. It is as much a Wayland Compositor as any of the others, if you want it to use it as such - by all means do so. If you want to write a minimal Wayland-only WM in Arcan, you can absolutely do so. You can use the code here for just that: https://github.com/letoram/arcan/blob/master/tests/interactive/wltest/wltest.lua

I would recommend against it as far as possible just from how deeply, fundamentally and irreparably flawed and inept the technology and "protocol" behind Wayland actually is; but there are people to this day that find a rationale behind using ASN1 so YMMV. Should Wayland "win" - whatever that means - nothing really changes. Should enough people one day kick the tires hard enough and realise that the emperor is naked, then I'll happily git rm src/wayland.

If anything, A12 is a competitor. It can be built and used entirely without the rest of Arcan. I know of at least one commercial product that does just that.

**Comment by letoram** [comment]
> Hello,
> 
> I have been using `awesomeWM` for years with great pleasure. But I switched to wayland so that
> I am now looking for something similar to it on the wayland side.

Hi, if I answered you on IRC already - you can disregard the rest in here, but if not:

> The nice feature I would like to have is to be able to extend in any ways the detop environment with lua,
> which was quite easy to do on `awesomeWM`
 > It seems to me, at first glance, that `durden`, together with `arcan`, could comply with this, am I right ?

Correct. It's not as mature, but if there is any feature found missing - it should be added. The Durden developer documentation is of much lower quality, but extending and customising it is much more powerful by the virtues of what the underlying engine provides versus X11.

> In addition, is it possible with `durden` to benefit from a touchscreen, i.e. being able to implement some gestures ? Even if not yet implemented.

While better continued in the Durden repository/issue tracker, you can configure and map gestures to most anything already (see devmaps/touch/*.lua for how that is done). You can also add your own custom gesture analysis/classifier into input/classifiers.

**Comment by deb75** [comment]
Hi

Thanks for your answer.

I am in the process of compiling `arcan`. It currently fails with : 
```
[ 49%] Linking C executable ../../afsrv_terminal
/usr/bin/ld: ../../lib/libfreetype.a(sfnt.c.o): référence au symbole non défini « BrotliDecoderDecompress »
/usr/bin/ld : /lib/x86_64-linux-gnu/libbrotlidec.so.1 : erreur lors de l'ajout de symboles : DSO manquant dans la ligne de commande
collect2: error: ld returned 1 exit status
make[2]: *** [frameserver/terminal/CMakeFiles/afsrv_terminal.dir/build.make:234 : afsrv_terminal] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:1067 : frameserver/terminal/CMakeFiles/afsrv_terminal.dir/all] Erreur 2
```

I try to compile on `debian/bulleyes`, all packages just upgraded. I noticed that `libbrotlidec` is not in `/lib/x86_64-linux-gnu/` but in `/usr/lib/x86_64-linux-gnu/`

Do you have a clue ?

Regarding `wayland`, I am not necessarily looking for to run with it by all means. According to what you said, what is the best way to run `arcan/durden` ?

Regards

**Comment by paronomazia** [comment]
I did a Debian 10 build today. This seemed to pull all required dependencies:

```bash
sudo apt update
sudo apt install -qy dialog apt-utils git pkg-config clang cmake \
    libfreetype6-dev libluajit-5.1-dev libopenal-dev libsqlite3-dev \
    libegl1-mesa-dev libgl1-mesa-dev libosmesa6-dev libgbm-dev \
    libxkbcommon-dev libwayland-server0 libavcodec-dev libavformat-dev \
    libswscale-dev libavfilter-dev libavdevice-dev libvlc-dev liblzma-dev \
    libvlccore-dev libvncserver-dev libbz2-dev libleptonica-dev \
    libtesseract-dev libwayland-dev wayland-protocols libxcb-composite0-dev \
    libxcb-cursor-dev libxcb-util0-dev libxcb1-dev libxcb-ewmh-dev \
    libxcb-icccm4-dev libdrm-dev libsdl2-dev
```

**Comment by deb75** [comment]
Thanks, successful build now.

**Comment by demostanis** [comment]
@deb75 Please build with `LC_ALL=C`. Not everyone speaks baguette here.
The recommended way of running Arcan is by executing the resulting binary after the compilation.
As for Durden, after having cloned its repository, simply run `arcan durden/durden`.
It's written in the [README](https://github.com/letoram/durden). Have you not read it?
