### ISSUE TITLE
(lua) load_image fails for jpeg files with extension 'jpeg' or 'JPEG'

### ISSUE THREAD

**Issue by salotz** [letoram/arcan#243]
Renaming the file `picture.jpeg` to `picture.jpg` results in a success so it is just something to do with the file extension recognition.

**Comment by salotz** [comment]
I don't quite understand what you mean by buffer underflow here. Wouldn't adding the `len >= 4` just be useful if there was other file extensions to check for, similar to the previous `len >= 3`?.

Also this should probably be discussed in the PR itself.

**Comment by letoram** [comment]
fixed in 31f2c32
