### ISSUE TITLE
arcan widget toolkit ?

### ISSUE THREAD

**Issue by alavaelian** [letoram/arcan#247]
is there is a widget toolkit for arcan ?

**Comment by letoram** [comment]
Complicated question to answer - yes and no. In a sense the TUI libraries (with their Lua bindings) is a limited set of widgets for Arcan >clients<. When it comes to the main engine and its Lua scripts, the general tactic is that the side projects (durden, safespaces, pipeworld) incubate UI primitives based on what they need for their own UIs.

When these get complete enough, they are to be cleaned up and merged into the main distribution as reusable support scripts - but that hasn't happened yet. There is a longer explanation as to why this is, but the underlying article is still months away (but ties into https://www.divergent-desktop.org/blog/2020/08/10/principles-overview/#p3)
